import:
  - orgs/demo/_defaults

settings:
  github:
    reviewers:
      - type: Team
        id: 6968536

vars:
  stage: prod
  environment: ue1

components:
  terraform:
    dummy:
      vars:
        seed: prod4
