name: 👽 Atmos GHA Plan Demo
run-name: 👽 Atmos GHA Plan Demo
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  atmos-affected:
    name: determine affected stacks
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.transform.outputs.affected }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: cloudposse/github-action-setup-atmos@v1.0.0
      - name: atmos affected stacks
        id: affected
        run: |
          atmos describe affected --file affected.json
      - name: transform affected output
        id: transform
        shell: bash
        run: |
          affected=$(jq -c '{include: [.[] | select(.component_type == "terraform")| {stack: .stack, component: .component, full_stack_name: (.stack + "-" + .component)}]}' < $(echo affected.json))
          echo "affected=$affected" >> $GITHUB_OUTPUT

  atmos-plan:
    runs-on: ubuntu-latest
    needs:
      - atmos-affected
    strategy:
      matrix: ${{ fromJson(needs.atmos-affected.outputs.affected) }}
    name: atmos plan ${{ matrix.full_stack_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: cloudposse/github-action-setup-atmos@v1.0.0
        with:
          install-wrapper: false

      - name: atmos plan
        id: atmos-plan
        run: |
          atmos terraform plan ${{ matrix.component }} -s ${{ matrix.stack }} -out=$(pwd)/${{ matrix.full_stack_name }}-${{github.sha}}.planfile

      - name: store plan
        uses: cloudposse/github-action-terraform-plan-storage@b0ed94088163b1a96be804db06258b9ffd8a0d00
        id: store-plan
        with:
          action: storePlan
          planPath: ${{ matrix.full_stack_name }}-${{github.sha}}.planfile
          component: ${{ matrix.component }}
          stack: ${{ matrix.stack }}
          tableName: demo-terraform-plan-storage
          bucketName: demo-terraform-plan-storage
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: create or update deployment environment
        shell: bash
        run: |
          payload=$(atmos describe stacks ${{ matrix.component }} -s ${{ matrix.stack }} --sections=settings --format json| jq -c 'keys[] as $k | .[$k].components.terraform | keys[] as $c | .[$c].settings.github')

          echo "$payload"

          curl \
            -sS \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.DEPLOYMENTS_GITHUB_TOKEN}}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{github.api_url}}/repos/${{github.repository}}/environments/${{matrix.full_stack_name}}" \
          -d "$payload"
