name: 👽 Atmos GHA Demo
run-name: 👽 Atmos GHA Demo
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  tf-plan:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v3
      # with:
      #   repository: ${{ github.event.pull_request.head.repo.full_name }}
      #   ref: ${{ github.event.pull_request.head.ref }}
      - uses: hashicorp/setup-terraform@v2
      - uses: cloudposse/github-action-setup-atmos@v1.0.0
      - run: |
          atmos 
