name: 👽 Atmos GHA Demo
run-name: 👽 Atmos GHA Demo
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  atmos-affected:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: cloudposse/github-action-setup-atmos@v1.0.0
      - name: atmos affected stacks
        id: affected
        run: |
          atmos describe affected
      - name: transform affected output
        id: transform
        run: |
          affected=$(echo ${{ steps.affected.outputs.stdout }}| jq -c)
          #jq --argjson j "${{ steps.affected.outputs.stdout }}" -r '[.[] | select(.component_type == "terraform")| {stack: .stack, component: .component, full_stack_name: (.stack + "-" + .component)}]')
          #echo "affected=$json" >> $GITHUB_OUTPUT
          echo "affected=$affected" >> $GITHUB_OUTPUT
    outputs:
      affected: ${{ steps.transform.outputs.affected }}

  atmos-plan:
    runs-on: ubuntu-latest
    needs:
      - atmos-affected
    strategy:
      matrix:
        stack: ${{ fromJson(needs.atmos-affected.outputs.affected) }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: cloudposse/github-action-setup-atmos@v1.0.0
      - id: atmos-plan
        run: |
          atmos terraform plan ${{ matrix.full_stack_name }} -out=${{ matrix.full_stack_name }}-${{github.sha}}.planfile
      - uses: cloudposse/github-action-terraform-plan-storage@feature/initial-implementation
        id: store-plan
        with:
          action: storePlan
          planPath: ${{ matrix.full_stack_name }}-${{github.sha}}.planfile
          component: ${{ matrix.component }}
          stack: ${{ matrix.stack }}
          tableName: demo-terraform-plan-storage
          bucketName: demo-terraform-plan-storage
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          AWS_REGION: us-east-1
